<<<<<<< HEAD
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - electron
  - esbuild
  - javascript-obfuscator
  - unrs-resolver
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
allowBuilds:
  '@parcel/watcher': true
>>>>>>> ff2bba6705f6e8d4882c9919916e7111f4f71dea
  unrs-resolver: true
  vue-demi: true
