<<<<<<< HEAD
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - electron
  - esbuild
  - javascript-obfuscator
  - unrs-resolver
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
allowBuilds:
  '@parcel/watcher': true
>>>>>>> c3dda85b40baa6188b2eff4e263cb20fedabcecf
  unrs-resolver: true
  vue-demi: true
