<<<<<<< HEAD
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - electron
  - esbuild
  - javascript-obfuscator
  - unrs-resolver
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
allowBuilds:
  '@parcel/watcher': true
>>>>>>> fd8153baf11ced5360854b92fb17395299e83151
  unrs-resolver: true
  vue-demi: true
